### ISSUE TITLE
[HELP] - Erreur lors du lancement du container enedisgatewaymqtt2

### ISSUE THREAD

**Issue by Zokoboo** [m4dm4rtig4n/enedisgateway2mqtt#123]
Bonjour, je dispose d'une installation de votre solution sur docker, lorsque je lance le container de enedisgateway , j'obtiens ce message d'erreurs dans les logs : 

Version de la passerelle : VERSION : 0.7.7

```
2022-08-23 10:22:18.218106 - INFO  : InfluxDB


Traceback (most recent call last):


  File "/app/main.py", line 515, in <module>


    for id, value in config['influxdb'].items():


AttributeError: 'NoneType' object has no attribute 'items'
```

je vous joins mon fichier configuration 

```
##########
# GLOBAL #
##########
debug: true

####################
##      MQTT      ##
####################
mqtt:
  host: 192.168.1.186       # MANDATORY
  port: 1883
  username: "mosquitto"
  password: "MDP"
  prefix: enedis_gateway
  client_id: enedis_gateway
  retain: true
  qos: 0

####################
## Home assistant ##
####################
home_assistant:
  discovery: false
  discovery_prefix: homeassistant
  card_myenedis: false

###############
## Influx DB ##
###############
influxdb: 
host: 192.168.1.186
port: 8086
token: enedis:MDP
org: "-"
bucket: linky/autogen

####################
## ENEDIS GATEWAY ##
####################
enedis_gateway:
  "XXXXXXXXXXXX":              # Replace XXXXXXXXXXXXXX by your PDL Number. MANDATORY
    token: "MONTOKEN"          # MANDATORY
    plan: BASE                 # BASE or HP/HC
    consumption: true                 
    consumption_detail: true         
    consumption_price_hc: 0.1296           
    consumption_price_hp: 0.1727           
    consumption_price_base: 0.1296         
    production: false                 
    production_detail: false          
    offpeak_hours: ""         # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-06h00;11h30-14h30
    addresses: true
#  YYYYYYYYYYYYYY:            # Replace YYYYYYYYYYYYYY by your other PDL Number
#    token: YOUR_TOKEN
#    plan: HP/HC
#    consumption: true
#    consumption_detail: true
#    consumption_price_hc: 0.1781
#    consumption_price_hp: 0.1337
#    consumption_price_base: 0.1781
#    production: false
#    production_detail: false
#    addresses: true
```

et voici mon docker-compose.yaml

```
# define a enedisgateway2mqtt  service
version: "3.8"

services:
  enedisgateway2mqtt:
    image: m4dm4rtig4n/enedisgateway2mqtt:latest
#   image: m4dm4rtig4n/enedisgateway2mqtt:latest-dev
    container_name: enedisgateway
    restart: unless-stopped
    volumes:
    - /home/docker/docker_compose/enedisgateway/data:/data

```

En vous souhaitant une agréable journée
Cordialement Rémy
