### ISSUE TITLE
Config.yaml : Valeurs par défaut non prises en compte

### ISSUE THREAD

**Issue by Nardol** [m4dm4rtig4n/enedisgateway2mqtt#60]
Certaines valeurs non requises doivent être définies, par exemple :
- Je dois définir le préfixe MQTT
- Même chose pour le préfixe pour l'auto-discover, si je l'active sans définir un préfixe j'ai une erreur.

J'ai arrêté après ce dernier donc je ne sais pas s'il y en a d'autres.

Pour l'auto-discovery par exemple, j'ai cette erreur :
```
Traceback (most recent call last):
  File "/app/main.py", line 622, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 203, in run
    ha.haAutodiscovery(client=client, type="sensor", pdl=pdl, name=key, value=data)
  File "/app/home_assistant.py", line 17, in haAutodiscovery
    "stat_t": f"{main.config['home_assistant']['discovery_prefix']}/{type}/enedisgateway/{pdl}_{name}/state",
KeyError: 'discovery_prefix'
```

**Comment by m4dm4rtig4n** [comment]
Tu peut me donner ton config.yml stp ?

**Comment by Nardol** [comment]
```yaml
cycle: 3600
debug: false
enedis_gateway:
  XXXXXXXXXXXXXX:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1484
    consumption_price_hc: 0.1263
    consumption_price_hp: 0.1678
    #offpeak_hours: null
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: true
    token: YYYYYYYYYYY
home_assistant:
  card_myenedis: true
  discovery: true
  #discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: "192.168.XX.YY"
  password: "passw"
  port: 1883
  #prefix: enedis_gateway
  qos: 0
  retain: false
  username: 'user'
```

Pas mal de valeurs définies dans leurs valeurs par défaut, serait-il utile de tester ce que ça donne en les commentant ?
