### ISSUE TITLE
[HELP] - for influxdb config 

### ISSUE THREAD

**Issue by aladin2000** [m4dm4rtig4n/enedisgateway2mqtt#63]
**What can I do for you?**
J'ai créé sous influxdb une base nommée linky avec le user qui va bien aisni que ses provilèges admin....
avec cette config, 
```
influxdb:
    host: influxdb
    port: 8086
    token: myUSERNAME/myPASSWORD
    org: "-"
    bucket: "linky/autogen"
```
malgré : les messages MQTT sent  je ne vois aucune mesurements dans la base .linky.. 
Est ce que tu pourrais STP m'en  donner qq explications ou en mode DEBUG à forcer pour  en comprendre la raison.... 

**Configuration**
```
influxdb:
    host: IP de nom serveur 
    port: 8086
    token: myUSERNAME/myPASSWORD
    org: "-"
    bucket: "linky/autogen"

```
**Installation type**
Docker or HassIO addons
HassIO addons
**Version : X.X.X**
0.7.6
