### ISSUE TITLE
EHELP] - erreur yaml 

### ISSUE THREAD

**Issue by mellowtronik** [m4dm4rtig4n/enedisgateway2mqtt#70]
**Description du bug**
Bonjour, 
Ayant tout ré installé (mqtt /mqtt brocker et enedisgateway2mqtt) j'ai configuré le fichier yaml et j'ai des erreurs, pourtant sur yamllint ça me dit que tout est bon. 
Je joins mon ficher yaml et la capture d'écran du message d'erreur. 

Merci 

Type d'installation* = HassIO dernière version. 

![Screenshot_2021-11-21-10-50-16-430_com android chrome](https://user-images.githubusercontent.com/91826922/142757566-d14142ee-c600-45fb-9836-1801a005439f.jpg)

**Comment by mellowtronik** [comment]
Yaml 
[yaml.txt](https://github.com/m4dm4rtig4n/enedisgateway2mqtt/files/7576055/yaml.txt)

**Comment by m4dm4rtig4n** [comment]
Tu as mal formaté ton YAML : 
```
enedis_gateway: 
  xxxxxxxxxxxxx:
    token: xxxxx
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: "0,1821"
    consumption_price_hc: "0,1360"
    consumption_price_hp: "0,1821"
    offpeak_hours: 22h36-6h36
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
```
